# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "ja-JP"
reviews:
  path_instructions:
    - path: "**/*.rb"
      instructions: |-
        # refactoring
        - まずFat Controllerを避け、次にFat Modelを避ける。
    - path: "test/**/*"
      instructions: |-
        # Test
        - TestCase名は英語で書く。
        - どうしても避けられない時以外にsystem testでsleepは使わない。
        # Unit Test
        model, helper, decorator, view_componentについてはメソッドを追加した場合は必ず対応したUnit TestのTestCaseを1つは書く。

