plugins:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-capybara

AllCops:
  NewCops: enable
  Exclude:
    - app/views/**/*
    - config/**/*
    - config.ru
    - node_modules/**/*
    - db/migrate/*
    - db/schema.rb
    - db/queue_schema.rb
    - db/cache_schema.rb
    - db/cable_schema.rb
    - storage/**/*
    - tmp/**/*
    - bin/**/*
